/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import static vista.MenuAdministrador.txtNombreUsuario;


/**
 *
 * @author estadm
 */
public class CRUDVeterinario extends javax.swing.JFrame {
    
    Controlador controlador =new Controlador();

    /**
     * Creates new form CRUDVeterinarioAdmin
     */
    public CRUDVeterinario() {
        initComponents();
        setLocationRelativeTo(null);
        txtUsuarioVeterinario.setEditable(false);
        btnCrearVeterinario.setEnabled(false);
        txtObtenerRolInicio.setVisible(false);
        txtObtenerUsuarioq1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDVeterinario = new javax.swing.JTextField();
        NombreVeterinario = new javax.swing.JTextField();
        Calificacion = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SitioWeb = new javax.swing.JTextField();
        TelefonoCliente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtUsuarioVeterinario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Provincia = new javax.swing.JTextField();
        Canton = new javax.swing.JTextField();
        Distrito = new javax.swing.JTextField();
        UGoogleMaps = new javax.swing.JTextField();
        Señas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnCrearVeterinario = new javax.swing.JButton();
        btnBuscarVeterinario = new javax.swing.JButton();
        btnBorrarUsuario = new javax.swing.JButton();
        btnActualizarVeterinario = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeterinario = new javax.swing.JTable();
        RedesSociales = new javax.swing.JButton();
        Horarios = new javax.swing.JButton();
        txtObtenerRolInicio = new javax.swing.JTextField();
        btnActivarBotones = new javax.swing.JButton();
        txtObtenerUsuarioq1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Administrar Veterinarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID de Veterinario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Teléfono");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sitio Web");

        IDVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        NombreVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Calificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Calificación");

        SitioWeb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TelefonoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TelefonoCliente.setText("Registrar teléfono");
        TelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoClienteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nombre de usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreVeterinario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Calificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IDVeterinario)
                    .addComponent(TelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Correo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SitioWeb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuarioVeterinario))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NombreVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TelefonoCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtUsuarioVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Provincia");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cantón");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Distrito");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Señas");

        Provincia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Canton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Distrito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Distrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistritoActionPerformed(evt);
            }
        });

        UGoogleMaps.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UGoogleMaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UGoogleMapsActionPerformed(evt);
            }
        });

        Señas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Señas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeñasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Ubicación");

        Estado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Estado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(UGoogleMaps)
                    .addComponent(Señas)
                    .addComponent(Distrito)
                    .addComponent(Canton)
                    .addComponent(Provincia))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Canton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Distrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Señas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UGoogleMaps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        btnCrearVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrearVeterinario.setText("Crear");
        btnCrearVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVeterinarioActionPerformed(evt);
            }
        });

        btnBuscarVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarVeterinario.setText("Buscar");
        btnBuscarVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVeterinarioActionPerformed(evt);
            }
        });

        btnBorrarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBorrarUsuario.setText("Borrar");
        btnBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUsuarioActionPerformed(evt);
            }
        });

        btnActualizarVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActualizarVeterinario.setText("Actualizar");
        btnActualizarVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVeterinarioActionPerformed(evt);
            }
        });

        Volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        tblVeterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IDVeterinario", "NombreVeterinario", "Calificacion", "Correo", "SitioWeb", "Distrito", "Canton", "Provincia", "Señas", "UGoogleMaps", "Estado", "NombreUsuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVeterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeterinarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVeterinario);

        RedesSociales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RedesSociales.setText("Registrar red social");
        RedesSociales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedesSocialesActionPerformed(evt);
            }
        });

        Horarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Horarios.setText("Registrar horario");
        Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosActionPerformed(evt);
            }
        });

        btnActivarBotones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActivarBotones.setText("Activar opciones");
        btnActivarBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarBotonesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RedesSociales)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Horarios)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtObtenerRolInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtObtenerUsuarioq1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnActivarBotones))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnCrearVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnBuscarVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnActualizarVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnBorrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(57, 57, 57))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)))
                        .addGap(0, 283, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCrearVeterinario)
                                    .addComponent(btnBuscarVeterinario))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnActualizarVeterinario)
                                    .addComponent(btnBorrarUsuario))
                                .addGap(36, 36, 36)
                                .addComponent(Volver)
                                .addGap(50, 50, 50)
                                .addComponent(btnActivarBotones)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RedesSociales)
                            .addComponent(Horarios)
                            .addComponent(txtObtenerRolInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObtenerUsuarioq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistritoActionPerformed

    private void UGoogleMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UGoogleMapsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UGoogleMapsActionPerformed

    private void btnCrearVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVeterinarioActionPerformed
        int idVeterinario = Integer.parseInt(this.IDVeterinario.getText());
        int calificacion = Integer.parseInt(this.Calificacion.getText());
        int ubicacionGM = Integer.parseInt(this.UGoogleMaps.getText());
        try {
            controlador.RegistrarVeterinario(idVeterinario, this.NombreVeterinario.getText(), calificacion, this.Correo.getText(), this.SitioWeb.getText(), this.Distrito.getText(), this.Canton.getText(), this.Provincia.getText(), this.Señas.getText(), ubicacionGM, this.Estado.getText() , this.txtUsuarioVeterinario.getText());
            limpiarTxt();
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CRUDVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearVeterinarioActionPerformed

    private void SeñasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeñasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeñasActionPerformed

    private void btnBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioActionPerformed
        // TODO add your handling code here:
        int idVeterinario = Integer.parseInt(this.IDVeterinario.getText());
        try {
                controlador.BorrarVeterinario(idVeterinario);
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CRUDVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBorrarUsuarioActionPerformed

    private void btnActualizarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVeterinarioActionPerformed
        // TODO add your handling code here:
        int idVeterinario = Integer.parseInt(this.IDVeterinario.getText());
        int calificacion = Integer.parseInt(this.Calificacion.getText());
        int ubicacionGM = Integer.parseInt(this.UGoogleMaps.getText());
        try {
            controlador.ActualizarVeterinario(idVeterinario, this.NombreVeterinario.getText(), calificacion, this.Correo.getText(), this.SitioWeb.getText(), this.Distrito.getText(), this.Canton.getText(), this.Provincia.getText(), this.Señas.getText(), ubicacionGM, this.Estado.getText() , this.txtUsuarioVeterinario.getText());
            limpiarTxt();
        } catch (SQLException | ClassNotFoundException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(CRUDVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarVeterinarioActionPerformed

    private void btnBuscarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVeterinarioActionPerformed
        String rol = txtObtenerRolInicio.getText();
        if(rol.equals("Veterinario")){
            cargarTabla1();
        }
        else{
            cargarTabla();
        }
    }//GEN-LAST:event_btnBuscarVeterinarioActionPerformed

    

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        String rol = txtObtenerRolInicio.getText();
        String ne = txtObtenerUsuarioq1.getText();
        
        if(rol.equals("Administrador")){
            MenuAdministrador ru = new MenuAdministrador();
            ru.setVisible(true);
            this.dispose();
            MenuAdministrador.txtOBtenerRol.setText(rol);
            MenuAdministrador.txtNombreUsuario.setText(ne);
        }
        else{
            MenuVeterinario ru = new MenuVeterinario();
            ru.setVisible(true);
            this.dispose();
            MenuVeterinario.txtRolInicio.setText(rol);
            MenuVeterinario.txtPruebaUsuario.setText(ne);
        }
        
    }//GEN-LAST:event_VolverActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void tblVeterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeterinarioMouseClicked
        // TODO add your handling code here:
        try{
            int fila = tblVeterinario.getSelectedRow();
            int id = Integer.parseInt(tblVeterinario.getValueAt(fila, 0).toString());
            PreparedStatement ps;
            ResultSet rs;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDVeterinario, NombreVeterinario, Calificacion, Correo, SitioWeb, Distrito, Canton, Provincia, Señas, UGoogleMaps, Estado, NombreUsuario FROM Veterinario WHERE IDVeterinario = ?");
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while(rs.next()){
                IDVeterinario.setText(String.valueOf(id));
                NombreVeterinario.setText(rs.getString("NombreVeterinario"));
                Calificacion.setText(rs.getString("Calificacion"));
                Correo.setText(rs.getString("Correo"));
                SitioWeb.setText(rs.getString("SitioWeb"));
                Distrito.setText(rs.getString("Distrito"));
                Canton.setText(rs.getString("Canton"));
                Provincia.setText(rs.getString("Provincia"));
                Señas.setText(rs.getString("Señas"));
                UGoogleMaps.setText(rs.getString("UGoogleMaps"));
                Estado.setText(rs.getString("Estado"));
                txtUsuarioVeterinario.setText(rs.getString("NombreUsuario"));
                          
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tblVeterinarioMouseClicked

    private void TelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoClienteActionPerformed
        String nu = this.IDVeterinario.getText();
        String ne = this.txtObtenerRolInicio.getText();
        String nn = this.txtObtenerUsuarioq1.getText();
        CRUDTelefonoVeterinario ru = new CRUDTelefonoVeterinario();
        ru.setVisible(true);
        this.dispose();
        CRUDTelefonoVeterinario.IDVeterinario.setText(nu);
        CRUDTelefonoVeterinario.txtRoltelVeterinario.setText(ne);
        CRUDTelefonoVeterinario.txtUserTelVeterinario.setText(nn);
        
    }//GEN-LAST:event_TelefonoClienteActionPerformed

    private void RedesSocialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedesSocialesActionPerformed
        String nu = this.IDVeterinario.getText();
        String ne = this.txtObtenerRolInicio.getText();
        String nn = this.txtObtenerUsuarioq1.getText();
        CRUDSocialesVeterinario ru = new CRUDSocialesVeterinario();
        ru.setVisible(true);
        this.dispose();
        CRUDSocialesVeterinario.IDVeterinario.setText(nu);
        CRUDSocialesVeterinario.txtROLRedesVet.setText(ne);
        CRUDSocialesVeterinario.txtUserRedesVet.setText(nn);
    }//GEN-LAST:event_RedesSocialesActionPerformed

    private void HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosActionPerformed
        String nu = this.IDVeterinario.getText();
        String ne = this.txtObtenerRolInicio.getText();
        String nn = this.txtObtenerUsuarioq1.getText();
        CRUDHorariosVeterinario ru = new CRUDHorariosVeterinario();
        ru.setVisible(true);
        this.dispose();
        CRUDHorariosVeterinario.IDVeterinario.setText(nu);
        CRUDHorariosVeterinario.txtROLHorario.setText(ne);
        CRUDHorariosVeterinario.txtUSERHorario.setText(nn);
    }//GEN-LAST:event_HorariosActionPerformed

    private void btnActivarBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarBotonesActionPerformed
        String nu = this.txtObtenerRolInicio.getText();
        if(nu.equals("Administrador")){
            txtUsuarioVeterinario.setEditable(true);
            btnCrearVeterinario.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Usted no puede habilitar estas opciones");
        }
    }//GEN-LAST:event_btnActivarBotonesActionPerformed

    private void limpiarTxt(){
        NombreVeterinario.setText("");
        Calificacion.setText("");
        Correo.setText("");
        SitioWeb.setText("");
        Distrito.setText("");
        Canton.setText("");
        Provincia.setText("");
        Señas.setText("");
        UGoogleMaps.setText("");
        Estado.setText("");
      }
    
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tblVeterinario.getModel();
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rmsd;
        int columnas;
        
        int[] anchos = {25, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50};
        for(int i = 0; i < tblVeterinario.getColumnCount();i++){
            tblVeterinario.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        //String user = IDVeterinario.getText();
        try{
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDVeterinario, NombreVeterinario, Calificacion, Correo, SitioWeb, Distrito, Canton, Provincia, Señas, UGoogleMaps, Estado, NombreUsuario FROM Veterinario");
            //ps.setString(1, user);
            rs = ps.executeQuery();
            rmsd = rs.getMetaData();
            columnas = rmsd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int indice = 0; indice < columnas; indice++){
                    fila[indice] = rs.getObject(indice+1);
                }
                modeloTabla.addRow(fila);
                
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void cargarTabla1(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tblVeterinario.getModel();
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rmsd;
        int columnas;
        
        int[] anchos = {25, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50};
        for(int i = 0; i < tblVeterinario.getColumnCount();i++){
            tblVeterinario.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        String user = txtUsuarioVeterinario.getText();
        try{
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDVeterinario, NombreVeterinario, Calificacion, Correo, SitioWeb, Distrito, Canton, Provincia, Señas, UGoogleMaps, Estado, NombreUsuario FROM Veterinario WHERE NombreUsuario = ?");
            ps.setString(1, user);
            rs = ps.executeQuery();
            rmsd = rs.getMetaData();
            columnas = rmsd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int indice = 0; indice < columnas; indice++){
                    fila[indice] = rs.getObject(indice+1);
                }
                modeloTabla.addRow(fila);
                
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
   
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Calificacion;
    private javax.swing.JTextField Canton;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Distrito;
    private javax.swing.JTextField Estado;
    private javax.swing.JButton Horarios;
    private javax.swing.JTextField IDVeterinario;
    private javax.swing.JTextField NombreVeterinario;
    private javax.swing.JTextField Provincia;
    private javax.swing.JButton RedesSociales;
    private javax.swing.JTextField Señas;
    private javax.swing.JTextField SitioWeb;
    private javax.swing.JButton TelefonoCliente;
    private javax.swing.JTextField UGoogleMaps;
    private javax.swing.JButton Volver;
    private javax.swing.JButton btnActivarBotones;
    private javax.swing.JButton btnActualizarVeterinario;
    private javax.swing.JButton btnBorrarUsuario;
    private javax.swing.JButton btnBuscarVeterinario;
    private javax.swing.JButton btnCrearVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVeterinario;
    public static javax.swing.JTextField txtObtenerRolInicio;
    public static javax.swing.JTextField txtObtenerUsuarioq1;
    public static javax.swing.JTextField txtUsuarioVeterinario;
    // End of variables declaration//GEN-END:variables
}
