/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;



/**
 *
 * @author estadm
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
        txtOBtenerRol.setVisible(false);
        txtNombreUsuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GestionVeterinario = new javax.swing.JButton();
        CRUDProcedimientos = new javax.swing.JButton();
        CRUDUsuarios = new javax.swing.JButton();
        btnCrudCitas = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        txtOBtenerRol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menú Administrador");

        GestionVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GestionVeterinario.setText("Gestión de veterinarios");
        GestionVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionVeterinarioActionPerformed(evt);
            }
        });

        CRUDProcedimientos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CRUDProcedimientos.setText("Gestión de categorías de servicios/procedimientos ");
        CRUDProcedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDProcedimientosActionPerformed(evt);
            }
        });

        CRUDUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CRUDUsuarios.setText("Gestión de usuarios");
        CRUDUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDUsuariosActionPerformed(evt);
            }
        });

        btnCrudCitas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrudCitas.setText("Gestión citas médicas");
        btnCrudCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudCitasActionPerformed(evt);
            }
        });

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CRUDProcedimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CRUDUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrudCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GestionVeterinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(txtOBtenerRol, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(GestionVeterinario)
                .addGap(18, 18, 18)
                .addComponent(CRUDProcedimientos)
                .addGap(18, 18, 18)
                .addComponent(CRUDUsuarios)
                .addGap(18, 18, 18)
                .addComponent(btnCrudCitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOBtenerRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CRUDUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDUsuariosActionPerformed
        String nn = txtOBtenerRol.getText();
        String ne = txtNombreUsuario.getText();
        CRUDUsuario ru = new CRUDUsuario();
        ru.setVisible(true);
        this.dispose();
        CRUDUsuario.txtRolUnirConAdmi.setText(nn);
        CRUDUsuario.txtUserUnirConAdmi.setText(ne);
    }//GEN-LAST:event_CRUDUsuariosActionPerformed

    private void CRUDProcedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDProcedimientosActionPerformed
        String nn = txtOBtenerRol.getText();
        String ne = txtNombreUsuario.getText();
        CRUDcategoriaProcedimientosServicios ru = new CRUDcategoriaProcedimientosServicios();
        ru.setVisible(true);
        this.dispose();
        CRUDcategoriaProcedimientosServicios.txtROL13.setText(nn);
        CRUDcategoriaProcedimientosServicios.txtUsuario12s.setText(ne);
        
    }//GEN-LAST:event_CRUDProcedimientosActionPerformed

    private void GestionVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionVeterinarioActionPerformed
        String nn = txtOBtenerRol.getText();
        String ne = txtNombreUsuario.getText();
            CRUDVeterinario ru = new CRUDVeterinario();
            ru.setVisible(true);
            this.dispose();
        CRUDVeterinario.txtObtenerRolInicio.setText(nn);
        CRUDVeterinario.txtObtenerUsuarioq1.setText(ne);
    }//GEN-LAST:event_GestionVeterinarioActionPerformed

    private void btnCrudCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudCitasActionPerformed
        String nu = this.txtOBtenerRol.getText();
        String nn = this.txtNombreUsuario.getText();
        CRUDCitas ru = new CRUDCitas();
        ru.setVisible(true);
        this.dispose();
        CRUDCitas.txtRolPrincipal.setText(nu);
        CRUDCitas.txtUsuarioVeterinario1.setText(nn);
    }//GEN-LAST:event_btnCrudCitasActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CRUDProcedimientos;
    private javax.swing.JButton CRUDUsuarios;
    private javax.swing.JButton GestionVeterinario;
    private javax.swing.JButton btnCrudCitas;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField txtNombreUsuario;
    public static javax.swing.JTextField txtOBtenerRol;
    // End of variables declaration//GEN-END:variables
}
