/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;



/**
 *
 * @author estadm
 */
public class MenuVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form Conexion
     */
    public MenuVeterinario() {
        initComponents();
        setLocationRelativeTo(null);
        txtPruebaUsuario.setVisible(false);
        txtRolInicio.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProcedimientoServicio = new javax.swing.JButton();
        btnGestionPaciente = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtPruebaUsuario = new javax.swing.JTextField();
        txtRolInicio = new javax.swing.JTextField();
        btnAdministrarMisDatosVeterinario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de veterinarios");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menú Veterinario");

        btnProcedimientoServicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProcedimientoServicio.setText("Gestión de procedimientos/Servicios");
        btnProcedimientoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcedimientoServicioActionPerformed(evt);
            }
        });

        btnGestionPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGestionPaciente.setText("Gestión y consulta de pacientes");
        btnGestionPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPacienteActionPerformed(evt);
            }
        });

        btnCitas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCitas.setText("Gestión de citas médicas");
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Consulta de clientes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtPruebaUsuario.setEditable(false);
        txtPruebaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPruebaUsuarioActionPerformed(evt);
            }
        });

        btnAdministrarMisDatosVeterinario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdministrarMisDatosVeterinario.setText("Administrar mis datos");
        btnAdministrarMisDatosVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarMisDatosVeterinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAdministrarMisDatosVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProcedimientoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(btnGestionPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtPruebaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRolInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcedimientoServicio)
                .addGap(18, 18, 18)
                .addComponent(btnGestionPaciente)
                .addGap(18, 18, 18)
                .addComponent(btnCitas)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(btnAdministrarMisDatosVeterinario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRolInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPruebaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcedimientoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcedimientoServicioActionPerformed
        String nu = this.txtPruebaUsuario.getText();
        String ne = this.txtRolInicio.getText();
        CRUDProcedimientoServicio ru = new CRUDProcedimientoServicio();
        ru.setVisible(true);
        this.dispose();
        CRUDProcedimientoServicio.txtUsuarioPro.setText(nu);
        CRUDProcedimientoServicio.txtROL231.setText(ne);
        
    }//GEN-LAST:event_btnProcedimientoServicioActionPerformed

    private void txtPruebaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPruebaUsuarioActionPerformed
        
    }//GEN-LAST:event_txtPruebaUsuarioActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        String nu = this.txtRolInicio.getText();
        String nn = this.txtPruebaUsuario.getText();
        CRUDCitas ru = new CRUDCitas();
        ru.setVisible(true);
        this.dispose();
        CRUDCitas.txtRolPrincipal.setText(nu);
        CRUDCitas.txtUsuarioVeterinario1.setText(nn);
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnGestionPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPacienteActionPerformed
        
        String nn = this.txtPruebaUsuario.getText();
        String ne = this.txtRolInicio.getText();
        CRUDPaciente ru = new CRUDPaciente();
        ru.setVisible(true);
        this.dispose();
        CRUDPaciente.txtUsuarioVeterinarioGestionPacientes.setText(nn);
        CRUDPaciente.txtRolPrincipal.setText(ne);
    }//GEN-LAST:event_btnGestionPacienteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nn = this.txtPruebaUsuario.getText();
        String ne = this.txtRolInicio.getText();
        ConsultaClientes ru = new ConsultaClientes();
        ru.setVisible(true);
        this.dispose();
        ConsultaClientes.txtUser1231k.setText(nn);
        ConsultaClientes.txtRolInicio23423.setText(ne);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAdministrarMisDatosVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarMisDatosVeterinarioActionPerformed
        String nu = this.txtPruebaUsuario.getText();
        String nn = this.txtRolInicio.getText();
        CRUDVeterinario ru = new CRUDVeterinario();
        ru.setVisible(true);
        this.dispose();
        CRUDVeterinario.txtUsuarioVeterinario.setText(nu);
        CRUDVeterinario.txtObtenerRolInicio.setText(nn);
        CRUDVeterinario.txtObtenerUsuarioq1.setText(nu);
    }//GEN-LAST:event_btnAdministrarMisDatosVeterinarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarMisDatosVeterinario;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnGestionPaciente;
    private javax.swing.JButton btnProcedimientoServicio;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField txtPruebaUsuario;
    public static javax.swing.JTextField txtRolInicio;
    // End of variables declaration//GEN-END:variables
}
